// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utenlzwsdwwdueycuxqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0ZW5sendzZHd3ZHVleWN1eHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1Njc4NjQsImV4cCI6MjA2MTE0Mzg2NH0.vaDx-ZMHNaSX04wbxoeqApC7lfh5sSQETn1_Z4ql6Wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);