// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwrmtukgjnsjxcojqmic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3cm10dWtnam5zanhjb2pxbWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTgzNTIsImV4cCI6MjA2MTY3NDM1Mn0.FD3dEFlobZu0OXBRGFG5AH-rxgvbk5FgHrzXlSSdRhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);